# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - monitorrent

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to registry
      uses: docker/login-action@v1
      with:
        registry: https://index.docker.io/v1/
        username: ${{ secrets.AzureAppService_ContainerUsername_db1ec6332c414fe6add74b693b72cb3f }}
        password: ${{ secrets.AzureAppService_ContainerPassword_68f58160f85a4cdfad515c7ac0f31d02 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: index.docker.io/${{ secrets.AzureAppService_ContainerUsername_db1ec6332c414fe6add74b693b72cb3f }}/monitorrent:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'monitorrent'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_9b94fa4e3660477a894df67d8b50f1c7 }}
        images: 'index.docker.io/${{ secrets.AzureAppService_ContainerUsername_db1ec6332c414fe6add74b693b72cb3f }}/monitorrent:${{ github.sha }}'